### PR TITLE
Make continue on query error optional

### PR DESCRIPTION
**Pull request by karailiev**
Adding option to allow the developer determine if execution should be stopped or continued on query error.
Default is set to true to ensure backward compatibility.

### CODE REVIEW

**Comment by iseus** [comment]
Hi,
Good addition, thank you.

Shortly this will needs a parameter object instead of attributes... ;)

**Comment by snapperben** [comment]
Iseus,

It works ok for your test data does it?

Ben

**Comment by iseus** [comment]
I'll check it tomorrow

**Comment by iseus** [comment]
It works. Good question if we would like to continue running the next sql statement on error or not, currently this additon just prevents gulp to exit if needed. But for this, it works perfectly.

**Comment by karailiev** [comment]
@iseus I think it should terminate very loudly.
But I saw it was removed intentionally in the past, so I decided to make it optional.
Even if we keep it optional, I would suggest to have it `FALSE` by default.

**Comment by iseus** [comment]
@karailiev You are right in this, usually an sql script builds on previous statements. If one is failing the rest would usually fail too. So let it as is now I think.

@snapperben you can accept the PR.

**Comment by snapperben** [comment]
@iseus Cheers .....will accept

@karailiev ...good work

**Pull request merged**
